### ISSUE TITLE
Move crate to RustCrypto/password-hashing?

### ISSUE THREAD

**Issue by newpavlov** [Keats/rust-bcrypt#10]
Greetings!

My name is Artyom Pavlov and I am maintainer of [RustCrypto](https://github.com/RustCrypto) organization. We have a repository for [password-hashing](https://github.com/RustCrypto/password-hashing) algorithms. Would you be interested in moving this crate to it? I think it will help to attract developers and additional attention to this crate. I can invite you to the organization as well if you are interested.

If your answer is yes, then it would be also nice to relicense crate under dual MIT/Apache 2.0 for conformity with other crates.

**Comment by Keats** [comment]
I'm not sure about that, the crate is pretty stable and the only change really needed would be to remove the dependency on rust-crypto as it's unmaintained but it's not urgent.
