### ISSUE TITLE
BcryptError doesn't implement std::error::Error

### ISSUE THREAD

**Issue by drusellers** [Keats/rust-bcrypt#2]
Is this by design or something you would accept a PR for?

**Comment by Keats** [comment]
That's an oversight, please do submit a PR!

**Comment by drusellers** [comment]
Submitted https://github.com/Keats/rust-bcrypt/pull/3

**Comment by Keats** [comment]
Published at 0.1.2, thanks!

**Comment by drusellers** [comment]
Working like a champ now!






On Sun, Nov 13, 2016 at 12:26 AM -0600, "Vincent Prouillet" <notifications@github.com> wrote:












Published at 0.1.2, thanks!

**Comment by euank** [comment]
I think this issue can be closed per above comments.
