### ISSUE TITLE
bcrypt::verify does not compare in constant time.

### ISSUE THREAD

**Issue by ElectronicRU** [Keats/rust-bcrypt#23]
The provided verify function does a comparison using ==, which is in my understanding a fail-fast compare. This is insecure and opens the way for a timing attack; password hash comparisons should always take constant time independent of value.

**Comment by Keats** [comment]
I don't think it's that necessary for bcrypt but I thought it already used constant time comparison, when it was actually in https://github.com/Keats/jsonwebtoken >_>
I'll take a PR for it or do it myself when I get some time

**Comment by Keats** [comment]
I've implemented something in https://github.com/Keats/rust-bcrypt/commit/4fef14c54bb58911683e2735d5f46c753c25c021 but afaik it might get optimised away
