### ISSUE TITLE
Truncation should result in an error

### ISSUE THREAD

**Issue by jonas-schievink** [Keats/rust-bcrypt#25]
Here, the input password gets truncated to 71 chars (72 with the added null terminator):

https://github.com/Keats/rust-bcrypt/blob/bf042b361aee3202033a9aeaf664558a11f77cd3/src/lib.rs#L56-L58

I don't think it's a good idea to silently do this. The function should return an error when the input is too long. This should also be loudly documented.

While it's unlikely that users will try to use 71 character passwords, this still presents a risk when an application feeds extra data into bcrypt, especially since it's not documented at all.

**Comment by Keats** [comment]
That's a limitation of the bcrypt algorithm and is the case in pretty much all implementations. In theory 71 bytes + 1 byte terminator.

This should be documented but it shouldn't result in an error, you wouldn't be able to validate passwords generated by another library otherwise.

**Comment by jonas-schievink** [comment]
The user could also explicitly truncate before calling `verify`, preventing the error

**Comment by Keats** [comment]
The crate should be able to verify existing hashes without getting an error by default. If you really don't want it to truncate, you can check before passing it to bcrypt.

**Comment by jonas-schievink** [comment]
What about making `hash` error on truncation, but not `verify`?

**Comment by Keats** [comment]
Then you can't hash things that can be done in other languages. Ideally we would have some default keyword argument like `error_on_truncate` on both but that's not possible in Rust. We could add a `strict_hash` and `strict_verify` that error that does the check however but I don't know if many people would use. There are better hashing functions now so bcrypt is usually used with existing codebases where the libraries generating them (most likely) do truncate. 

A common thing to do to avoid truncation is to, for example, `bcrypt::hash(sha256(&input))` and `bcrypt::verify(sha256(&input))` (https://github.com/pyca/bcrypt/#maximum-password-length for example)

**Comment by jonas-schievink** [comment]
> Then you can't hash things that can be done in other languages.

Sure, if you truncate before doing it. The asymmetry between the two function isn't very nice, though.

> We could add a strict_hash and strict_verify that error that does the check

Or alternatively, make them always do the check and add `truncating_hash` and `truncating_verify` that don't. I like this option more because it makes users opt into the potentially dangerous behavior instead of making them opt out. It does mean a breaking change though, while the `strict_*` versions avoid that.

> There are better hashing functions now so bcrypt is usually used with existing codebases

That's interesting, which ones are there? I've only really seen scrypt as a potentially better alternative so far.

**Comment by Keats** [comment]
> Sure, if you truncate before doing it. The asymmetry between the two function isn't very nice, though.

Right but the default behaviour should be to be compatible with other existing codebase. If you name one function `verify` and one function `truncating_verify`, people are going to use the first one and wonder why their python library can verify but here it throws an error. Even with documentation.

> That's interesting, which ones are there? I've only really seen scrypt as a potentially better alternative so far.

scrypt and argon2. If I were starting a new project I would use argon2.
