### ISSUE TITLE
I would like to have some default user, how can I generate the same password using bash?

### ISSUE THREAD

**Issue by GopherJ** [Keats/rust-bcrypt#26]
Hello, I'm using `bcrypt` to hash the registered user's password, but I also would like to have some default user in interactive way (ask the user to give the admin user/pass). But how can I generate the same password using bash?

**Comment by GopherJ** [comment]
I tried something like this:
```
sudo apt-get install apache2-utils
htpasswd -bnBC 12 "" xxxx | tr -d ':\n' 
```
but it's not the same with the one generated by `rust-bcrypt`.

Here is my code:
````
use bcrypt::{hash, verify, DEFAULT_COST};
let hash_password = hash(&msg.password, DEFAULT_COST)
```

**Comment by Keats** [comment]
The `hash` function generates a random salt so you're not going to generate the exact same hash. You should be able to `verify` it however.

**Comment by GopherJ** [comment]
@Keats yes finally I understood this point, but it seems verification always fails, any ideas on generating pre-defined accounts?

I need multiple accounts by default and let the administrator to manager the their passwords during installation.
