### ISSUE TITLE
Help with bcrypt::verify

### ISSUE THREAD

**Issue by JordiOfRivia** [Keats/rust-bcrypt#27]
Hey, all

I'm a writing an auth system with rocket and diesel. i use bcrypt to hash the password this works fine.
But now i'm struggling on how to verify the hash password with the login password.
I have now something like this:

i'm getting the users password from the database with diesel
  let checkuser = users.filter(username.eq(login._username.to_string())).select(password).first(&connection);

now i want to verify both passwords
if bcrypt::verify(checkuser, login._password).unwrap()

but that gives me the following errors:

"the trait `std::convert::AsRef<[u8]>` is not implemented for `std::result::Result<_, diesel::result::Error>`"
"expected &str, found enum `std::result::Result"

Can someody help me with my problem?

**Comment by Keats** [comment]
I don't know diesel but `checkuser` is a Result, so you need to add a `?`, `match` or `unwrap/expect` to get the actual string. It should work afterwards
