### ISSUE TITLE
Possibility of choosing the type of RNG?

### ISSUE THREAD

**Issue by knowdbtech** [Keats/rust-bcrypt#28]
Hi,

I just would like to suggest the possibility to choose the RNG used to generate the random number used in the cryptography process.

I did some performance tests with this lib and for multiple request in a web service that encrypt a password for example and, in my computer, at the beginning of the tests the program handle around 10 requests per sec to crypt a pass with default cost, but after some time with constant requests the number of requests handled decreases drastically like 0.25 req per sec, maybe that happens because the entropy pool of the OS emptied in view of the use of the OsRng from rand to generate random numbers.

According to the documentation of rand (https://rust-random.github.io/rand/rand/rngs/index.html) there are other options to generate secure random numbers like ThreadRng and StdRng instead of OsRng. All of this three options use  CSPRNG but the others are faster than OsRng.

As a suggestion we could inform to the hash method which RNG to use to generate random numbers, the default could be the OsRng as well. This way we can optimize the performance of the system and keep it safe.

**Comment by Keats** [comment]
Sounds like a good idea, how would that look in practice? I don't want to force people to select a RNG type in the function. Maybe a `hash_with_rng` function that takes an enum of allowed RNGs (which would be implement in this crate) to avoid allowing usage of insecure RNGs. This way we do not expose `rand` at all to the end user

**Comment by Keats** [comment]
@knowdbtech any chance you can do a PR for that?

**Comment by knowdbtech** [comment]
> Maybe a hash_with_rng function that takes an enum of allowed RNGs (which would be implement in this crate) to avoid allowing usage of insecure RNGs. This way we do not expose rand at all to the end user.

Sounds a great idea and yes, I can do a PR for that.

**Comment by mverleg** [comment]
What about just ``hash_with_salt``? It's very easy to use and lets people use whatever source of randomness they wish. Including using a static value for unit tests.
