### ISSUE TITLE
hash_with_result

### ISSUE THREAD

**Issue by mverleg** [Keats/rust-bcrypt#37]
I noticed that ``hash_with_result`` returns ``HashParts``, but it seems that ``HashParts`` has only private fields, and ``format_for_version`` is also private.

Is there anything that can be done with this method, that can't be done with just `hash`?

**Comment by Keats** [comment]
I think it was made public by accident, it can be removed in a breaking change version.

**Comment by mverleg** [comment]
Okay, I thought because there are multiple versions, maybe they were meant to be exposed. But no action needed for now then.
