### ISSUE TITLE
Add a hash parsing feature

### ISSUE THREAD

**Issue by kompass** [Keats/rust-bcrypt#41]
Hello ! I'm working on a project using bcrypt for zero-knowledge proofs, and I need to verify the integrity of the hashes I receive from another application, and to check if the cost is greater than a given cost. I would want to do it properly, using the features you implemented, but with a private scope. I think other people might need it too.

Do you agree if I propose a pull request making some of the private features public, by implementing a proper interface ? I ask before to avoid to having to do development for nothing.

**Comment by kompass** [comment]
I need it anyway so I implemented it.

**Comment by Keats** [comment]
Released in 0.7.0
