### ISSUE TITLE
Question on the default version change

### ISSUE THREAD

**Issue by alexfedoseev** [Keats/rust-bcrypt#50]
In the `0.6.0`, there was a change in default version from `2y` to `2b`. I have existing userbase with hashes that were generated with the previous default version `2y`. Should I opt-out of the new default and stay on the same version during crate update or I can switch to the new default and `verify` would work for both: old hashes generated with the old default version and the new hashes generated with the new default?

**Comment by Keats** [comment]
verify will work for both, I think you should be fine staying on the default

**Comment by alexfedoseev** [comment]
Thanks!
