### ISSUE TITLE
Zeroize optional

### ISSUE THREAD

**Issue by danielhuang** [Keats/rust-bcrypt#69]
Zeroize was implemented based on #68 and using #67. This introduces an additional dependency and causes a slight performance bottleneck.

Ideally, this should be behind a feature flag.

**Comment by Keats** [comment]
It would have to be opt-out as it would lower the security to remove it.

**Comment by danielhuang** [comment]
`zeroize` as a default feature would make this opt-out.

**Comment by Keats** [comment]
Yep, I would take a PR for it.
