### ISSUE TITLE
It would be nice to see a Changelog file that calls out breaking changes

### ISSUE THREAD

**Issue by tapickell** [Keats/rust-bcrypt#73]
Tonic has a really good example of a helpful Changelog file
[Changelog.md](https://github.com/hyperium/tonic/blob/master/CHANGELOG.md)

As an engineer with a project that depends on this crate
When dependa-bot creates a PR to update to the latest version
I should be able to find a Changelog file that indicates what has changed between versions
So I can be sure the update will not break any functionality the app is using.

**Comment by Keats** [comment]
Something like https://github.com/Keats/rust-bcrypt#changelog ?
