### ISSUE TITLE
Verifying password without hash

### ISSUE THREAD

**Issue by mlthlschr** [Keats/rust-bcrypt#77]
Hi,

I am trying to tackle the problem of time-based attack in an app of mine. 

The way I am currently handling authentication is by querying the database for the users hash and compare it to the given password via `bcrypt::verify`. However, if there is no such user in the db, I do not get any hash to compare to, which means I have to skip the verification. And that means the function is returning way faster than when verifying.

Is there a different way how to handle this? I could generate some kind of bogus hash to compare to, but that seems kind of hacky.

**Comment by Keats** [comment]
> Is there a different way how to handle this? I could generate some kind of bogus hash to compare to, but that seems kind of hacky.

I think it's probably the least hacky way?

**Comment by mlthlschr** [comment]
Okay, thanks. But but I wonder if that is the way how everybody else does it?

**Comment by Keats** [comment]
I think most people don't handle that kind of time based attack since the reset password feature often leak whether a user is signed up or not already, depending on the implementation.
