### ISSUE TITLE
password hash including slash returns InvalidHash

### ISSUE THREAD

**Issue by Daku-on** [Keats/rust-bcrypt#78]
I try to make a web app with password authentication by bcrypt 0.14.0.
https://github.com/Daku-on/chatgpt_actix/blob/d14a084d3a40c8a4b308417ee30030f6827f77d3/bcrypt_bugreport.rs
Here is the main.rs and for example `.env` file is following (it was hashed by bcrypt);
`APP_PASSWORD_HASH=$2b$12$hlgb/v0rqXvs3dIQjTeQF.2Q/ZZJvUeSak0fORk6/3ki1Flhuatom`

I post password by postman and get an error says 

> `thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHash("/v0rqXvs3dIQjTeQF.2Q/ZZJvUeSak0fORk6/3ki1Flhuatom")', src/main.rs:29:49`

It seems hash was cut off before the first slash (/) of the hash and I'm afraid this is not what I would like to be.

If this is not comming from bcrypt I'm sorry for causing you trouble. Thank you.

**Comment by Keats** [comment]
I don't get an invalid hash when I try to verify that hash so the error is probably before passing it to the library where the hash is truncated somehow

**Comment by Daku-on** [comment]
I got it. Thank you so much for your time!
