### ISSUE TITLE
rustc-serialize is deprecated

### ISSUE THREAD

**Issue by shssoichiro** [Keats/rust-bcrypt#8]
The `rustc-serialize` crate is [deprecated](https://github.com/rust-lang-deprecated/rustc-serialize), and this crate should be migrated to use [`base64`](https://github.com/alicemaz/rust-base64) instead

**Comment by Keats** [comment]
Uploaded 0.1.4 which uses base64 instead, thanks!

Sadly rust-crypto is not maintained too but I can't find another implementation of bcrypt
